### PR TITLE
Darker pretty-pastebin

### PR DESCRIPTION
**Pull request by bflee890**
Creates a version pretty pastebin that is darker
image

### CODE REVIEW

**Comment by evanpurkhiser** [comment]
Nice, a few things blee:
1. Can you squash the two commits together so it's just one?
2. I think we can do even better with the colors. There are some pretty contrasting colors here that could probably be changed to play nicely with the whole overall theme.
   - The border color should definitely be changed to something more complementary
   - Same for the page background, it's less of an appealing grey and more of just a... grey.
   - The link color and text color in the header could be cleaned up.
   - The download glyph should also be changed to the same color as the title text color. This should be pretty easy since the glyph is just embedded in the css. Same goes for the little clipboard glyph in the top left, though that should probably be tweaked a bit not to be the exact same color as the text.
   - I think some colors of the actual diff content might need some tweaking. The background doesn't really feel like it plays nicely with the off grey of the content.

These are just some thoughts off the top of my head. I might take a shot at my own dark version at some point too.

**Comment by bflee890** [comment]
I made some changes along with squashing all the changes into one commit
image

**Comment by bflee890** [comment]
image

**Comment by bflee890** [comment]
Fixed the shitty bottom left and right corners
image

**Comment by evanpurkhiser** [comment]
Looks good. Thanks

**Pull request merged**
